name: Craftory
version: 1.0.0
description: Plugin Extended Framework
author: Brett Saunders
main: studio.craftory.core.Craftory
api-version: 1.17

commands:
  spawnItem:
    description: Spawns a custom or normal Item.
    permission: craftory.items.spawnItem
    aliases: [give, i]
    usage: /<spawnItem> <name> <amount>

permissions:
  craftory.item.spawnItem:
    description: Allows you to spawn items
    default: op

libraries:
  - 'ch.jalu:injector:1.0'