name: CraftoryExample
main: studio.craftory.craftoryexample.CraftoryExamplePlugin
version: ${project.version}
api-version: 1.13
authors: [Brett Saunders, Mathew Jones]
depend: [Craftory]

commands:
  simplegen:
    description: Spawans a new Simple Generator Block above your head
    usage: /<command>
    permission: craftoryexample.simplegen